services:
  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CRAI_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "6900:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "6901:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

