services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "6901:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    # depends_on:
    #   - node-red
    networks:
      - app-network

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai
    volumes:
      - ./ai:/app
    ports:
      - "6902:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=local
    networks:
      - app-network
    restart: unless-stopped

  #cloud-sql-proxy:
    #image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
    #container_name: cloud-sql-proxy
    #volumes:
     # - ./gcp/service-account.json:/config/service-account.json:ro
    #command:
     # - "/cloud_sql_proxy"
     # - "-instances=crai-479909:europe-southwest1:root=tcp:0.0.0.0:3306"
     # - "-credential_file=/config/service-account.json"
    #networks:
     # - app-network
    #restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: backend
    ports:
      - "6903:1880"
    volumes:
      - ./backend/node_red_data:/data
    environment:
      - TZ=Europe/Madrid
    # env_file:
      #- ./backend/.env
    #depends_on:
      #- cloud-sql-proxy
      # - ebapi
    networks:
      - app-network
    restart: unless-stopped

  ebapi:
    build:
      context: ./ebAPI
      dockerfile: Dockerfile
    container_name: ebAPI
    ports:
      - "6904:8000"
    volumes:
      - ./ebAPI:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    restart: unless-stopped

  os:
    build:
      context: ./os
      dockerfile: Dockerfile
    container_name: os
    ports:
      - "6905:8080"
    # depends_on:
    #   - node-red
    networks:
      - app-network
    restart: unless-stopped

  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    container_name: docs
    ports:
      - "6910:4321"
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crai
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

