sonar.projectKey=crai-ebAPI
sonar.organization=crai123

sonar.projectName=ebAPI
sonar.projectVersion=1.0

# Paths are relative to ebAPI/
sonar.sources=.
sonar.tests=tests

sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/tests/**,**/__pycache__/**,**/data/**,**/coverage/**,**/htmlcov/**
sonar.sourceEncoding=UTF-8
