sonar.projectKey=crai-os
sonar.organization=crai123

sonar.projectName=os
sonar.projectVersion=1.0

# Paths are relative to os/
sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/docs/**
sonar.sourceEncoding=UTF-8
