export type Payment = {
  id: string
  amount: number
  status: "pending" | "processing" | "success" | "failed"
  email: string
  name: string
  date: string
}

const data: Payment[] = [
  {
    id: "m5gr84i9",
    amount: 316,
    status: "success",
    email: "ken99@example.com",
    name: "Ken Thompson",
    date: "2024-11-15",
  },
  {
    id: "3u1reuv4",
    amount: 242,
    status: "success",
    email: "abe45@example.com",
    name: "Abraham Lincoln",
    date: "2024-11-20",
  },
  {
    id: "derv1ws0",
    amount: 837,
    status: "processing",
    email: "monserrat44@example.com",
    name: "Monserrat Diaz",
    date: "2024-11-22",
  },
  {
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "silas22@example.com",
    name: "Silas Harper",
    date: "2024-11-18",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@example.com",
    name: "Carmella Soprano",
    date: "2024-11-10",
  },
  {
    id: "8f3h9k2l",
    amount: 456,
    status: "success",
    email: "david.wong@example.com",
    name: "David Wong",
    date: "2024-11-25",
  },
  {
    id: "p9q2r5s8",
    amount: 189,
    status: "pending",
    email: "emma.rodriguez@example.com",
    name: "Emma Rodriguez",
    date: "2024-11-28",
  },
  {
    id: "t6u7v8w9",
    amount: 923,
    status: "processing",
    email: "lucas.martinez@example.com",
    name: "Lucas Martinez",
    date: "2024-11-21",
  },
  {
    id: "x1y2z3a4",
    amount: 567,
    status: "success",
    email: "olivia.brown@example.com",
    name: "Olivia Brown",
    date: "2024-11-19",
  },
  {
    id: "b5c6d7e8",
    amount: 342,
    status: "failed",
    email: "noah.johnson@example.com",
    name: "Noah Johnson",
    date: "2024-11-12",
  },
  {
    id: "f9g0h1i2",
    amount: 678,
    status: "success",
    email: "sophia.davis@example.com",
    name: "Sophia Davis",
    date: "2024-11-23",
  },
  {
    id: "j3k4l5m6",
    amount: 234,
    status: "pending",
    email: "liam.garcia@example.com",
    name: "Liam Garcia",
    date: "2024-11-27",
  },
  {
    id: "n7o8p9q0",
    amount: 891,
    status: "processing",
    email: "ava.miller@example.com",
    name: "Ava Miller",
    date: "2024-11-16",
  },
  {
    id: "r1s2t3u4",
    amount: 445,
    status: "success",
    email: "ethan.wilson@example.com",
    name: "Ethan Wilson",
    date: "2024-11-24",
  },
  {
    id: "v5w6x7y8",
    amount: 156,
    status: "failed",
    email: "mia.moore@example.com",
    name: "Mia Moore",
    date: "2024-11-11",
  },
  {
    id: "z9a0b1c2",
    amount: 789,
    status: "success",
    email: "james.taylor@example.com",
    name: "James Taylor",
    date: "2024-11-17",
  },
  {
    id: "d3e4f5g6",
    amount: 523,
    status: "pending",
    email: "isabella.anderson@example.com",
    name: "Isabella Anderson",
    date: "2024-11-26",
  },
  {
    id: "h7i8j9k0",
    amount: 612,
    status: "processing",
    email: "william.thomas@example.com",
    name: "William Thomas",
    date: "2024-11-14",
  },
  {
    id: "l1m2n3o4",
    amount: 298,
    status: "success",
    email: "charlotte.jackson@example.com",
    name: "Charlotte Jackson",
    date: "2024-11-13",
  },
  {
    id: "p5q6r7s8",
    amount: 934,
    status: "failed",
    email: "benjamin.white@example.com",
    name: "Benjamin White",
    date: "2024-11-09",
  },
  {
    id: "a1b2c3d4",
    amount: 412,
    status: "success",
    email: "harper.lee@example.com",
    name: "Harper Lee",
    date: "2024-11-29",
  },
  {
    id: "e5f6g7h8",
    amount: 678,
    status: "processing",
    email: "mason.clark@example.com",
    name: "Mason Clark",
    date: "2024-11-28",
  },
  {
    id: "i9j0k1l2",
    amount: 234,
    status: "pending",
    email: "amelia.lewis@example.com",
    name: "Amelia Lewis",
    date: "2024-11-27",
  },
  {
    id: "m3n4o5p6",
    amount: 891,
    status: "success",
    email: "elijah.walker@example.com",
    name: "Elijah Walker",
    date: "2024-11-26",
  },
  {
    id: "q7r8s9t0",
    amount: 567,
    status: "failed",
    email: "evelyn.hall@example.com",
    name: "Evelyn Hall",
    date: "2024-11-08",
  },
  {
    id: "u1v2w3x4",
    amount: 345,
    status: "processing",
    email: "alexander.allen@example.com",
    name: "Alexander Allen",
    date: "2024-11-25",
  },
  {
    id: "y5z6a7b8",
    amount: 789,
    status: "success",
    email: "abigail.young@example.com",
    name: "Abigail Young",
    date: "2024-11-24",
  },
  {
    id: "c9d0e1f2",
    amount: 456,
    status: "pending",
    email: "daniel.king@example.com",
    name: "Daniel King",
    date: "2024-11-29",
  },
  {
    id: "g3h4i5j6",
    amount: 923,
    status: "success",
    email: "emily.wright@example.com",
    name: "Emily Wright",
    date: "2024-11-23",
  },
  {
    id: "k7l8m9n0",
    amount: 178,
    status: "failed",
    email: "matthew.lopez@example.com",
    name: "Matthew Lopez",
    date: "2024-11-07",
  },
  {
    id: "o2p3q4r5",
    amount: 634,
    status: "success",
    email: "victoria.scott@example.com",
    name: "Victoria Scott",
    date: "2024-11-22",
  },
  {
    id: "s6t7u8v9",
    amount: 445,
    status: "processing",
    email: "henry.green@example.com",
    name: "Henry Green",
    date: "2024-11-21",
  },
  {
    id: "w0x1y2z3",
    amount: 823,
    status: "pending",
    email: "grace.adams@example.com",
    name: "Grace Adams",
    date: "2024-11-29",
  },
  {
    id: "a4b5c6d7",
    amount: 512,
    status: "success",
    email: "samuel.baker@example.com",
    name: "Samuel Baker",
    date: "2024-11-20",
  },
  {
    id: "e8f9g0h1",
    amount: 289,
    status: "failed",
    email: "chloe.nelson@example.com",
    name: "Chloe Nelson",
    date: "2024-11-06",
  },
  {
    id: "i2j3k4l5",
    amount: 756,
    status: "processing",
    email: "jack.carter@example.com",
    name: "Jack Carter",
    date: "2024-11-19",
  },
  {
    id: "m6n7o8p9",
    amount: 398,
    status: "success",
    email: "lily.mitchell@example.com",
    name: "Lily Mitchell",
    date: "2024-11-18",
  },
  {
    id: "q0r1s2t3",
    amount: 667,
    status: "pending",
    email: "logan.perez@example.com",
    name: "Logan Perez",
    date: "2024-11-28",
  },
  {
    id: "u4v5w6x7",
    amount: 845,
    status: "success",
    email: "zoe.roberts@example.com",
    name: "Zoe Roberts",
    date: "2024-11-17",
  },
  {
    id: "y8z9a0b1",
    amount: 223,
    status: "failed",
    email: "ryan.turner@example.com",
    name: "Ryan Turner",
    date: "2024-11-05",
  },
  {
    id: "c2d3e4f5",
    amount: 934,
    status: "processing",
    email: "hannah.phillips@example.com",
    name: "Hannah Phillips",
    date: "2024-11-16",
  },
  {
    id: "g6h7i8j9",
    amount: 567,
    status: "success",
    email: "nathan.campbell@example.com",
    name: "Nathan Campbell",
    date: "2024-11-15",
  },
  {
    id: "k0l1m2n3",
    amount: 412,
    status: "pending",
    email: "aria.parker@example.com",
    name: "Aria Parker",
    date: "2024-11-27",
  },
  {
    id: "o4p5q6r7",
    amount: 789,
    status: "success",
    email: "caleb.evans@example.com",
    name: "Caleb Evans",
    date: "2024-11-14",
  },
  {
    id: "s8t9u0v1",
    amount: 156,
    status: "failed",
    email: "scarlett.edwards@example.com",
    name: "Scarlett Edwards",
    date: "2024-11-04",
  },
  {
    id: "w2x3y4z5",
    amount: 678,
    status: "processing",
    email: "dylan.collins@example.com",
    name: "Dylan Collins",
    date: "2024-11-13",
  },
  {
    id: "a6b7c8d9",
    amount: 523,
    status: "success",
    email: "penelope.stewart@example.com",
    name: "Penelope Stewart",
    date: "2024-11-12",
  },
  {
    id: "e0f1g2h3",
    amount: 891,
    status: "pending",
    email: "isaac.sanchez@example.com",
    name: "Isaac Sanchez",
    date: "2024-11-26",
  },
  {
    id: "i4j5k6l7",
    amount: 345,
    status: "success",
    email: "layla.morris@example.com",
    name: "Layla Morris",
    date: "2024-11-11",
  },
  {
    id: "m8n9o0p1",
    amount: 712,
    status: "failed",
    email: "owen.rogers@example.com",
    name: "Owen Rogers",
    date: "2024-11-03",
  },
  {
    id: "q2r3s4t5",
    amount: 445,
    status: "success",
    email: "aurora.reed@example.com",
    name: "Aurora Reed",
    date: "2024-11-10",
  },
  {
    id: "u6v7w8x9",
    amount: 678,
    status: "processing",
    email: "grayson.cook@example.com",
    name: "Grayson Cook",
    date: "2024-11-09",
  },
  {
    id: "y0z1a2b3",
    amount: 234,
    status: "pending",
    email: "hazel.morgan@example.com",
    name: "Hazel Morgan",
    date: "2024-11-29",
  },
  {
    id: "c4d5e6f7",
    amount: 891,
    status: "success",
    email: "elias.bell@example.com",
    name: "Elias Bell",
    date: "2024-11-08",
  },
  {
    id: "g8h9i0j1",
    amount: 567,
    status: "failed",
    email: "nova.murphy@example.com",
    name: "Nova Murphy",
    date: "2024-11-02",
  },
  {
    id: "k2l3m4n5",
    amount: 723,
    status: "processing",
    email: "easton.bailey@example.com",
    name: "Easton Bailey",
    date: "2024-11-07",
  },
  {
    id: "o6p7q8r9",
    amount: 412,
    status: "success",
    email: "violet.rivera@example.com",
    name: "Violet Rivera",
    date: "2024-11-06",
  },
  {
    id: "s0t1u2v3",
    amount: 856,
    status: "pending",
    email: "hudson.cooper@example.com",
    name: "Hudson Cooper",
    date: "2024-11-28",
  },
  {
    id: "w4x5y6z7",
    amount: 345,
    status: "success",
    email: "luna.richardson@example.com",
    name: "Luna Richardson",
    date: "2024-11-05",
  },
  {
    id: "a8b9c0d1",
    amount: 189,
    status: "failed",
    email: "maverick.cox@example.com",
    name: "Maverick Cox",
    date: "2024-11-01",
  },
  {
    id: "e2f3g4h5",
    amount: 934,
    status: "processing",
    email: "stella.howard@example.com",
    name: "Stella Howard",
    date: "2024-11-04",
  },
  {
    id: "i6j7k8l9",
    amount: 612,
    status: "success",
    email: "asher.ward@example.com",
    name: "Asher Ward",
    date: "2024-11-03",
  },
  {
    id: "m0n1o2p3",
    amount: 478,
    status: "pending",
    email: "willow.torres@example.com",
    name: "Willow Torres",
    date: "2024-11-27",
  },
  {
    id: "q4r5s6t7",
    amount: 756,
    status: "success",
    email: "theo.peterson@example.com",
    name: "Theo Peterson",
    date: "2024-10-31",
  },
  {
    id: "u8v9w0x1",
    amount: 298,
    status: "failed",
    email: "ivy.gray@example.com",
    name: "Ivy Gray",
    date: "2024-10-30",
  },
  {
    id: "y2z3a4b5",
    amount: 845,
    status: "processing",
    email: "axel.ramirez@example.com",
    name: "Axel Ramirez",
    date: "2024-10-29",
  },
  {
    id: "c6d7e8f9",
    amount: 523,
    status: "success",
    email: "ruby.james@example.com",
    name: "Ruby James",
    date: "2024-10-28",
  },
  {
    id: "g0h1i2j3",
    amount: 667,
    status: "pending",
    email: "leo.watson@example.com",
    name: "Leo Watson",
    date: "2024-11-26",
  },
  {
    id: "k4l5m6n7",
    amount: 389,
    status: "success",
    email: "aurora.brooks@example.com",
    name: "Aurora Brooks",
    date: "2024-10-27",
  },
  {
    id: "o8p9q0r1",
    amount: 712,
    status: "failed",
    email: "felix.kelly@example.com",
    name: "Felix Kelly",
    date: "2024-10-26",
  },
  {
    id: "s2t3u4v5",
    amount: 934,
    status: "processing",
    email: "sage.sanders@example.com",
    name: "Sage Sanders",
    date: "2024-10-25",
  },
  {
    id: "w6x7y8z9",
    amount: 456,
    status: "success",
    email: "jasper.price@example.com",
    name: "Jasper Price",
    date: "2024-10-24",
  },
  {
    id: "a0b1c2d3",
    amount: 623,
    status: "pending",
    email: "alice.bennett@example.com",
    name: "Alice Bennett",
    date: "2024-11-25",
  },
  {
    id: "e4f5g6h7",
    amount: 789,
    status: "success",
    email: "miles.wood@example.com",
    name: "Miles Wood",
    date: "2024-10-23",
  },
  {
    id: "i8j9k0l1",
    amount: 234,
    status: "failed",
    email: "clara.barnes@example.com",
    name: "Clara Barnes",
    date: "2024-10-22",
  },
  {
    id: "m2n3o4p5",
    amount: 867,
    status: "processing",
    email: "silas.ross@example.com",
    name: "Silas Ross",
    date: "2024-10-21",
  },
  {
    id: "q6r7s8t9",
    amount: 445,
    status: "success",
    email: "piper.henderson@example.com",
    name: "Piper Henderson",
    date: "2024-10-20",
  },
  {
    id: "u0v1w2x3",
    amount: 578,
    status: "pending",
    email: "atticus.coleman@example.com",
    name: "Atticus Coleman",
    date: "2024-11-24",
  },
  {
    id: "y4z5a6b7",
    amount: 912,
    status: "success",
    email: "juniper.jenkins@example.com",
    name: "Juniper Jenkins",
    date: "2024-10-19",
  },
  {
    id: "c8d9e0f1",
    amount: 367,
    status: "failed",
    email: "finn.perry@example.com",
    name: "Finn Perry",
    date: "2024-10-18",
  },
  {
    id: "g2h3i4j5",
    amount: 723,
    status: "processing",
    email: "maeve.powell@example.com",
    name: "Maeve Powell",
    date: "2024-10-17",
  },
  {
    id: "k6l7m8n9",
    amount: 489,
    status: "success",
    email: "oliver.long@example.com",
    name: "Oliver Long",
    date: "2024-10-16",
  },
  {
    id: "o0p1q2r3",
    amount: 634,
    status: "pending",
    email: "cora.patterson@example.com",
    name: "Cora Patterson",
    date: "2024-11-23",
  },
  {
    id: "s4t5u6v7",
    amount: 801,
    status: "success",
    email: "archer.hughes@example.com",
    name: "Archer Hughes",
    date: "2024-10-15",
  },
  {
    id: "w8x9y0z1",
    amount: 278,
    status: "failed",
    email: "daisy.flores@example.com",
    name: "Daisy Flores",
    date: "2024-10-14",
  },
  {
    id: "a2b3c4d5",
    amount: 923,
    status: "processing",
    email: "levi.washington@example.com",
    name: "Levi Washington",
    date: "2024-10-13",
  },
  {
    id: "e6f7g8h9",
    amount: 512,
    status: "success",
    email: "rose.butler@example.com",
    name: "Rose Butler",
    date: "2024-10-12",
  },
  {
    id: "i0j1k2l3",
    amount: 678,
    status: "pending",
    email: "declan.simmons@example.com",
    name: "Declan Simmons",
    date: "2024-11-22",
  },
  {
    id: "m4n5o6p7",
    amount: 356,
    status: "success",
    email: "iris.foster@example.com",
    name: "Iris Foster",
    date: "2024-10-11",
  },
  {
    id: "q8r9s0t1",
    amount: 745,
    status: "failed",
    email: "august.gonzales@example.com",
    name: "August Gonzales",
    date: "2024-10-10",
  },
  {
    id: "u2v3w4x5",
    amount: 489,
    status: "processing",
    email: "poppy.bryant@example.com",
    name: "Poppy Bryant",
    date: "2024-10-09",
  },
  {
    id: "y6z7a8b9",
    amount: 867,
    status: "success",
    email: "lincoln.alexander@example.com",
    name: "Lincoln Alexander",
    date: "2024-10-08",
  },
  {
    id: "c0d1e2f3",
    amount: 234,
    status: "pending",
    email: "magnolia.russell@example.com",
    name: "Magnolia Russell",
    date: "2024-11-21",
  },
  {
    id: "g4h5i6j7",
    amount: 612,
    status: "success",
    email: "wesley.griffin@example.com",
    name: "Wesley Griffin",
    date: "2024-10-07",
  },
  {
    id: "k8l9m0n1",
    amount: 423,
    status: "failed",
    email: "eden.diaz@example.com",
    name: "Eden Diaz",
    date: "2024-10-06",
  },
  {
    id: "o2p3q4r5",
    amount: 778,
    status: "processing",
    email: "brooks.hayes@example.com",
    name: "Brooks Hayes",
    date: "2024-10-05",
  },
  {
    id: "s6t7u8v9",
    amount: 545,
    status: "success",
    email: "julia.myers@example.com",
    name: "Julia Myers",
    date: "2024-10-04",
  },
  {
    id: "w0x1y2z3",
    amount: 891,
    status: "pending",
    email: "river.ford@example.com",
    name: "River Ford",
    date: "2024-11-20",
  },
  {
    id: "a4b5c6d7",
    amount: 367,
    status: "success",
    email: "evangeline.hamilton@example.com",
    name: "Evangeline Hamilton",
    date: "2024-10-03",
  },
]

export default data