sonar.projectKey=crai-itvAPI
sonar.organization=crai123

sonar.projectName=itvAPI
sonar.projectVersion=1.0

# Paths are relative to itvAPI/
sonar.sources=.
sonar.tests=tests

sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/tests/**,**/__pycache__/**,**/data/**,**/coverage/**,**/htmlcov/**
sonar.sourceEncoding=UTF-8
